### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dinhokusanagi** [flattool/warehouse#24] opened 2023-09-30 18:18 UTC
I would like to congratulate your work, it is really very good.

If your application could install the application via the flathub repository it would be a complete manager, I know that this may not be your project vision and I don't know how complicated the implementation must be, but I leave here my thoughts.

**Comment by kra-mo** [comment] 2023-10-01 05:15
Duplicate of #20

**Closed** 2023-10-01 05:15 UTC
Labels: duplicate, enhancement
